In [23]:
import numpy as np
a = np.array([1,2,3])
b = [1,2,3]
c = np.array([4,5,6])

print(a*5)
print(b*5)
print(a*c)
print(a+c)
print(a**c)

r = np.arange(10) #il metodo arrange crea un array di numeri da 0 a 9
print(r[2:8:3]) #questo for crea un array con gli elementi da 2 a 8 con step 3 e stampa l'array
print(r[::-1]) #questo for crea un array con gli elementi da 0 a 9 con step -1 e stampa l'array

r[3:5]=99 #r[3:5] è un array con gli elementi da 3 a 5, e gli assegno il valore 99
print(r)

I = np.array([[1,2,3], [0,0,0] ,[3,2,1]]) #np.array crea una matrice, in questo caso 3x3 con i valori indicati tra parentesi quadre 
I[0:2, 0:2] +=5
print(I[0:2, 0:2])
print(I)

for row in I: 
    for col in row:
        print(col)#stampa tutti gli elementi della matrice
        
for x in np.nditer(I): #nditer è un iteratore che permette di scorrere tutti gli elementi di una matrice
    print(x)
    
for x in I.flatten(): #flatten è un metodo che permette di scorrere tutti gli elementi di una matrice
    print(x)
    
for pos,x in np.ndenumerate(I): #ndenumerate è un iteratore che permette di scorrere tutti gli elementi di una matrice, ma restituisce anche la posizione
    print(pos,x)#qui si può accedere all'indice e al valore dell'elemento corrente
    i, j = pos #l'indice è una tupla, perchè la matrice è bidimensionale
    x = 0
    I[i,j]= 0 #azzera tutti gli elementi della matrice
    
print(I.T)
    
#ora dobbiamo scrivere un algoritmo che calcoli la trasposta di una matrice






[ 5 10 15]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[ 4 10 18]
[5 7 9]
[  1  32 729]
[2 5]
[9 8 7 6 5 4 3 2 1 0]
[ 0  1  2 99 99  5  6  7  8  9]
[[6 7]
 [5 5]]
[[6 7 3]
 [5 5 0]
 [3 2 1]]
6
7
3
5
5
0
3
2
1
6
7
3
5
5
0
3
2
1
6
7
3
5
5
0
3
2
1
(0, 0) 6
(0, 1) 7
(0, 2) 3
(1, 0) 5
(1, 1) 5
(1, 2) 0
(2, 0) 3
(2, 1) 2
(2, 2) 1
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
I[0:2, 0:2] +=5
print(I)

F = I.copy() #copy è un metodo che permette di copiare una matrice byte per byte

for pos, x in np.ndenumerate(I):
    i, j = pos
    F[j,i] = x #x==I[i,j]
    
print("la sua trasposta è:\n", F)



[[5 5 0]
 [5 5 0]
 [0 0 0]]
la sua trasposta è:
 [[5 5 0]
 [5 5 0]
 [0 0 0]]


In [29]:
%pip install opencv-python

  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np
I = np.arange(40000) #crea un array di numeri da 0 a 39999
I = I.reshape((200,200)) #reshape è un metodo che permette di cambiare le dimensioni di una matrice, in questo caso la matrice I viene trasformata in una matrice 200x200

I = np.zeros_like(I).astype(np.uint8) #crea una matrice di zeri con le stesse dimensioni di I, e la converte in unsigned int 8 bit
I[50:100, 50:100] += 100 #la matrice I è una matrice di zeri, quindi qui sto aggiungendo 100 a tutti gli elementi della matrice che hanno coordinate tra 50 e 100
I[:, 70:80] += 100 #aggiunge 100 a tutti gli elementi della matrice che hanno coordinate tra 70 e 80
I[:, 70:80] += 100
I[:100:5] += 100

import cv2

cv2.imshow("I", I) #mostra la matrice I
cv2.waitKey(0) #mostra la matrice I finchè non viene premuto un tasto




AttributeError: 'NoneType' object has no attribute 'shape'

In [22]:
import cv2

I = cv2.imread("Coat_of_arms_of_Ireland.svg.png")
print(I.shape)

I[:200,:,[0,2]] = 0
I[300:400, 300:400, 0] = 0
I[300:400, 300:400, 1] = 0
I[300:400, 300:400, 2] = 255

I[550:, 600:] = [50,0,150]
I[:,:,2] += 30

I//=2
I+=128

I[I > 255] = 255

cv2.imshow("I", I)
cv2.waitKey(0)

(1038, 800, 3)


-1